### PR TITLE
Needed setuptools

### PR DESCRIPTION
**Pull request by fabio-t**
A couple of minor changes.

Most importantly, I've switched to setuptools to make the markdown readme work.

Without it, we would either have to rewrite the readme in RST format, or keep the long description of the package empty. Moving to setuptools seemed the best option (no API change, as you can see).

### CODE REVIEW

**Comment by jhkorhonen** [comment]
Merged changes; bumped the version number to 1.9.4.1.

**Comment by fabio-t** [comment]
This works fine (this is only the test repository for PyPi):

https://test.pypi.org/project/MOODS-python/

See if you want other "aestethic" modifications (additional metadata on the sidebar, or modifications to the README?). If not, I can deploy the latest version to the actual PyPi repo.

**Comment by jhkorhonen** [comment]
Looks good to me! Please go ahead and deploy it to PyPi.

And thanks very much for all of your help with the PyPi package in general!

**Comment by fabio-t** [comment]
Done :)

**Pull request merged**
